# Generated by Django 4.1 on 2023-04-17 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.models.Inhabitant


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inhabitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('date_entrance', models.DateField()),
                ('date_leave', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enrolment_preference', models.JSONField(default=src.models.Inhabitant.default_enrolment_preference)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('nickname', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Debitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('debitors', models.ManyToManyField(related_name='involved_expenses', through='src.Debitor', to='src.inhabitant')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to='src.inhabitant')),
            ],
        ),
        migrations.AddField(
            model_name='debitor',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.expense'),
        ),
        migrations.AddField(
            model_name='debitor',
            name='inhabitant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='src.inhabitant'),
        ),
        migrations.AlterUniqueTogether(
            name='debitor',
            unique_together={('inhabitant', 'expense')},
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('icon', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='src.expensecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debitor',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.expense')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('ready_at', models.TimeField()),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooked_meals', to='src.inhabitant')),
                ('expense', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.expense')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=100)),
                ('num_guests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inhabitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='src.inhabitant')),
                ('value', models.BooleanField()),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('date', 'inhabitant')},
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
