# Generated by Django 4.1 on 2023-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_squashed_0015_alter_enrolment_value_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='num_guests',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='value',
        ),
        migrations.AddField(
            model_name='enrolment',
            name='n',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
