# Generated by Django 4.1 on 2023-06-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_remove_enrolment_num_guests_remove_enrolment_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inhabitant',
            name='start_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
