# Generated by Django 4.1 on 2024-04-03 22:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('src', '0018_expenserating_alter_expense_total_amount_and_more'), ('src', '0019_mealrating_delete_expenserating')]

    dependencies = [
        ('src', '0017_inhabitant_start_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('category', 1)), fields=('category', 'date'), name='single_meal_expense'),
        ),
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inhabitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='src.inhabitant')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='src.meal')),
            ],
            options={
                'unique_together': {('meal', 'inhabitant')},
            },
        ),
    ]
