export interface Inhabitant {
	id: number | null,
	username: string,
	password: string,
	email: string,
	first_name: string,
	last_name: string,
	nickname: string,
	language: string,
	date_of_birth: string,
	date_entrance: string,
	date_leave: string | null,
	is_superuser: boolean,
	enrolment_preference: {
		0: number,
		1: number,
		2: number,
		3: number,
		4: number,
		5: number,
		6: number,
	},
	start_balance: number,
}
