from .InhabitantSerializer import InhabitantSerializer
from .ExpenseSerializer import ExpenseSerializer
from .DebitorSerializer import DebitorSerializer
from .ExpenseCategorySerializer import ExpenseCategorySerializer
from .MealSerializer import MealSerializer
from .EnrolmentSerializer import EnrolmentSerializer
